# -*- coding: utf-8 -*-
"""Conjuntos_discretas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kuwk1eBiy16hagCtMj0gGhZvMre9tR2X

Juan Esteban Valdés Ospina

Importar librerias necesarias:
"""

from matplotlib import pyplot as plt 
from matplotlib_venn import venn2,venn3

"""Definir conjuntos y codigos necesarios:"""

def conjunto1():
    G = {30, 15, 10, 45}
    B = {15,100,40}
    U = {30, 50, 0, 15, 100, 40, 10, 80, 70, 45, 20, 60, 55}
    a = 0
  

    resultado1 = (B | (U - G))
    print(f" {resultado1}")
    for x in resultado1:
        a += x
    print(f"el numero de mujeres que son de estrato 3 o no tienen hijos son: {a} \n")

    v = venn2((1, 1, 1),set_colors=('#00909e', '#f67280'),set_labels=("B", "G"))
    v.get_label_by_id("11").set_text(B & G)
    v.get_label_by_id("10").set_text(B - G)
    v.get_label_by_id("01").set_text(G - B)
    v.get_label_by_id("11").set_color("#61AB7D")
    v.get_label_by_id("10").set_color("#61AB7D")
    plt.title(U- (B | G)).set_color("#61AB7D")
    plt.show()


def conjunto2():
    A = {30,50,0}
    E = {0,40,70,60}
    G = {30,15,10,45}
    U = {30, 50, 0, 15, 100, 40, 10, 80, 70, 45, 20, 60, 55}
    a = 0

    resultado2 = (U-(A|E) ^ (G | E))
    print(f"{resultado2}")
    for x in resultado2:
        a += x
    print(f"el numero de mujeres que, o no son de estrato 4 o tienen 2 o más hijos o, son mujeres que, no tienen hijos o tienen 2 o más hijos son: {a} \n")

    def lista():
        list: list[str] = [(A - (E | G)), ((A & E) - G), (E - (A | G)), (A & E & G), ((G & A) - E), ((G & E) - A),(G - (A | E))]
        for x in range(len(list)):
            if list[x] == set():
                list[x] = "{}"
        return list
    list = lista()

    v = venn3((1, 1, 1, 1, 1, 1, 1),set_labels=("A", "E", "G"), set_colors=('#00909e', '#f67280',"#96be25"))
    v.get_label_by_id("100").set_text(list[0])
    v.get_label_by_id("110").set_text(list[1])
    v.get_label_by_id("010").set_text(list[2])
    v.get_label_by_id("111").set_text(list[3])
    v.get_label_by_id("101").set_text(list[4])
    v.get_label_by_id("011").set_text(list[5])
    v.get_label_by_id("001").set_text(list[6])
    v.get_label_by_id("110").set_color("#61AB7D")
    v.get_label_by_id("101").set_color("#61AB7D")
    v.get_label_by_id("010").set_color("#61AB7D")
    plt.title(U- (A | E | G)).set_color("#61AB7D")

    plt.show()

"""Ejecución:"""

print("Punto 1 \n")
print("A:")
conjunto1()
print("B:")
conjunto2()

